// This file is @generated automatically by build.rs; do not edit manually.

use crate::domain::country::iso_country::IsoCountryStatic;

/// All ISO country rows statically loaded at compile time
pub const ISO_COUNTRIES: &[IsoCountryStatic] = &[
    IsoCountryStatic {
        country_code: 4,
        country_alpha2: "AF",
        country_alpha3: "AFG",
        country_eng_name: "Afghanistan",
        country_currency: 971,
        phone_prefix: "93",
        country_flag: "🇦🇫",
        is_country: true,
        country_primary_language: 128,
    },
    IsoCountryStatic {
        country_code: 8,
        country_alpha2: "AL",
        country_alpha3: "ALB",
        country_eng_name: "Albania",
        country_currency: 8,
        phone_prefix: "355",
        country_flag: "🇦🇱",
        is_country: true,
        country_primary_language: 5,
    },
    IsoCountryStatic {
        country_code: 12,
        country_alpha2: "DZ",
        country_alpha3: "DZA",
        country_eng_name: "Algeria",
        country_currency: 12,
        phone_prefix: "213",
        country_flag: "🇩🇿",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 16,
        country_alpha2: "AS",
        country_alpha3: "ASM",
        country_eng_name: "American Samoa",
        country_currency: 840,
        phone_prefix: "1",
        country_flag: "🇦🇸",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 20,
        country_alpha2: "AD",
        country_alpha3: "AND",
        country_eng_name: "Andorra",
        country_currency: 978,
        phone_prefix: "376",
        country_flag: "🇦🇩",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 24,
        country_alpha2: "AO",
        country_alpha3: "AGO",
        country_eng_name: "Angola",
        country_currency: 973,
        phone_prefix: "244",
        country_flag: "🇦🇴",
        is_country: true,
        country_primary_language: 129,
    },
    IsoCountryStatic {
        country_code: 28,
        country_alpha2: "AG",
        country_alpha3: "ATG",
        country_eng_name: "Antigua and Barbuda",
        country_currency: 951,
        phone_prefix: "1",
        country_flag: "🇦🇬",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 31,
        country_alpha2: "AZ",
        country_alpha3: "AZE",
        country_eng_name: "Azerbaijan",
        country_currency: 944,
        phone_prefix: "994",
        country_flag: "🇦🇿",
        is_country: true,
        country_primary_language: 14,
    },
    IsoCountryStatic {
        country_code: 32,
        country_alpha2: "AR",
        country_alpha3: "ARG",
        country_eng_name: "Argentina",
        country_currency: 32,
        phone_prefix: "54",
        country_flag: "🇦🇷",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 36,
        country_alpha2: "AU",
        country_alpha3: "AUS",
        country_eng_name: "Australia",
        country_currency: 36,
        phone_prefix: "61",
        country_flag: "🇦🇺",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 40,
        country_alpha2: "AT",
        country_alpha3: "AUT",
        country_eng_name: "Austria",
        country_currency: 978,
        phone_prefix: "43",
        country_flag: "🇦🇹",
        is_country: true,
        country_primary_language: 52,
    },
    IsoCountryStatic {
        country_code: 44,
        country_alpha2: "BS",
        country_alpha3: "BHS",
        country_eng_name: "Bahamas",
        country_currency: 44,
        phone_prefix: "1",
        country_flag: "🇧🇸",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 48,
        country_alpha2: "BH",
        country_alpha3: "BHR",
        country_eng_name: "Bahrain",
        country_currency: 48,
        phone_prefix: "973",
        country_flag: "🇧🇭",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 50,
        country_alpha2: "BD",
        country_alpha3: "BGD",
        country_eng_name: "Bangladesh",
        country_currency: 50,
        phone_prefix: "880",
        country_flag: "🇧🇩",
        is_country: true,
        country_primary_language: 19,
    },
    IsoCountryStatic {
        country_code: 51,
        country_alpha2: "AM",
        country_alpha3: "ARM",
        country_eng_name: "Armenia",
        country_currency: 51,
        phone_prefix: "374",
        country_flag: "🇦🇲",
        is_country: true,
        country_primary_language: 9,
    },
    IsoCountryStatic {
        country_code: 52,
        country_alpha2: "BB",
        country_alpha3: "BRB",
        country_eng_name: "Barbados",
        country_currency: 52,
        phone_prefix: "1",
        country_flag: "🇧🇧",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 56,
        country_alpha2: "BE",
        country_alpha3: "BEL",
        country_eng_name: "Belgium",
        country_currency: 978,
        phone_prefix: "32",
        country_flag: "🇧🇪",
        is_country: true,
        country_primary_language: 39,
    },
    IsoCountryStatic {
        country_code: 60,
        country_alpha2: "BM",
        country_alpha3: "BMU",
        country_eng_name: "Bermuda",
        country_currency: 60,
        phone_prefix: "1",
        country_flag: "🇧🇲",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 64,
        country_alpha2: "BT",
        country_alpha3: "BTN",
        country_eng_name: "Bhutan",
        country_currency: 64,
        phone_prefix: "975",
        country_flag: "🇧🇹",
        is_country: true,
        country_primary_language: 40,
    },
    IsoCountryStatic {
        country_code: 68,
        country_alpha2: "BO",
        country_alpha3: "BOL",
        country_eng_name: "Bolivia, Plurinational State of",
        country_currency: 68,
        phone_prefix: "591",
        country_flag: "🇧🇴",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 70,
        country_alpha2: "BA",
        country_alpha3: "BIH",
        country_eng_name: "Bosnia and Herzegovina",
        country_currency: 977,
        phone_prefix: "387",
        country_flag: "🇧🇦",
        is_country: true,
        country_primary_language: 22,
    },
    IsoCountryStatic {
        country_code: 72,
        country_alpha2: "BW",
        country_alpha3: "BWA",
        country_eng_name: "Botswana",
        country_currency: 72,
        phone_prefix: "267",
        country_flag: "🇧🇼",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 74,
        country_alpha2: "BV",
        country_alpha3: "BVT",
        country_eng_name: "Bouvet Island",
        country_currency: 578,
        phone_prefix: "47",
        country_flag: "🇧🇻",
        is_country: false,
        country_primary_language: 115,
    },
    IsoCountryStatic {
        country_code: 76,
        country_alpha2: "BR",
        country_alpha3: "BRA",
        country_eng_name: "Brazil",
        country_currency: 986,
        phone_prefix: "55",
        country_flag: "🇧🇷",
        is_country: true,
        country_primary_language: 129,
    },
    IsoCountryStatic {
        country_code: 84,
        country_alpha2: "BZ",
        country_alpha3: "BLZ",
        country_eng_name: "Belize",
        country_currency: 84,
        phone_prefix: "501",
        country_flag: "🇧🇿",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 86,
        country_alpha2: "IO",
        country_alpha3: "IOT",
        country_eng_name: "British Indian Ocean Territory",
        country_currency: 840,
        phone_prefix: "246",
        country_flag: "🇮🇴",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 90,
        country_alpha2: "SB",
        country_alpha3: "SLB",
        country_eng_name: "Solomon Islands",
        country_currency: 90,
        phone_prefix: "677",
        country_flag: "🇸🇧",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 92,
        country_alpha2: "VG",
        country_alpha3: "VGB",
        country_eng_name: "Virgin Islands (British)",
        country_currency: 826,
        phone_prefix: "1",
        country_flag: "🇻🇬",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 96,
        country_alpha2: "BN",
        country_alpha3: "BRN",
        country_eng_name: "Brunei Darussalam",
        country_currency: 96,
        phone_prefix: "673",
        country_flag: "🇧🇳",
        is_country: true,
        country_primary_language: 101,
    },
    IsoCountryStatic {
        country_code: 100,
        country_alpha2: "BG",
        country_alpha3: "BGR",
        country_eng_name: "Bulgaria",
        country_currency: 975,
        phone_prefix: "359",
        country_flag: "🇧🇬",
        is_country: true,
        country_primary_language: 24,
    },
    IsoCountryStatic {
        country_code: 104,
        country_alpha2: "MM",
        country_alpha3: "MMR",
        country_eng_name: "Myanmar",
        country_currency: 104,
        phone_prefix: "95",
        country_flag: "🇲🇲",
        is_country: true,
        country_primary_language: 25,
    },
    IsoCountryStatic {
        country_code: 108,
        country_alpha2: "BI",
        country_alpha3: "BDI",
        country_eng_name: "Burundi",
        country_currency: 108,
        phone_prefix: "257",
        country_flag: "🇧🇮",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 112,
        country_alpha2: "BY",
        country_alpha3: "BLR",
        country_eng_name: "Belarus",
        country_currency: 933,
        phone_prefix: "375",
        country_flag: "🇧🇾",
        is_country: true,
        country_primary_language: 18,
    },
    IsoCountryStatic {
        country_code: 116,
        country_alpha2: "KH",
        country_alpha3: "KHM",
        country_eng_name: "Cambodia",
        country_currency: 116,
        phone_prefix: "855",
        country_flag: "🇰🇭",
        is_country: true,
        country_primary_language: 80,
    },
    IsoCountryStatic {
        country_code: 120,
        country_alpha2: "CM",
        country_alpha3: "CMR",
        country_eng_name: "Cameroon",
        country_currency: 950,
        phone_prefix: "237",
        country_flag: "🇨🇲",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 124,
        country_alpha2: "CA",
        country_alpha3: "CAN",
        country_eng_name: "Canada",
        country_currency: 124,
        phone_prefix: "1",
        country_flag: "🇨🇦",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 132,
        country_alpha2: "CV",
        country_alpha3: "CPV",
        country_eng_name: "Cabo Verde",
        country_currency: 132,
        phone_prefix: "238",
        country_flag: "🇨🇻",
        is_country: true,
        country_primary_language: 129,
    },
    IsoCountryStatic {
        country_code: 136,
        country_alpha2: "KY",
        country_alpha3: "CYM",
        country_eng_name: "Cayman Islands",
        country_currency: 136,
        phone_prefix: "1",
        country_flag: "🇰🇾",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 140,
        country_alpha2: "CF",
        country_alpha3: "CAF",
        country_eng_name: "Central African Republic",
        country_currency: 950,
        phone_prefix: "236",
        country_flag: "🇨🇫",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 144,
        country_alpha2: "LK",
        country_alpha3: "LKA",
        country_eng_name: "Sri Lanka",
        country_currency: 144,
        phone_prefix: "94",
        country_flag: "🇱🇰",
        is_country: true,
        country_primary_language: 144,
    },
    IsoCountryStatic {
        country_code: 148,
        country_alpha2: "TD",
        country_alpha3: "TCD",
        country_eng_name: "Chad",
        country_currency: 950,
        phone_prefix: "235",
        country_flag: "🇹🇩",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 152,
        country_alpha2: "CL",
        country_alpha3: "CHL",
        country_eng_name: "Chile",
        country_currency: 990,
        phone_prefix: "56",
        country_flag: "🇨🇱",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 156,
        country_alpha2: "CN",
        country_alpha3: "CHN",
        country_eng_name: "China",
        country_currency: 156,
        phone_prefix: "86",
        country_flag: "🇨🇳",
        is_country: true,
        country_primary_language: 30,
    },
    IsoCountryStatic {
        country_code: 158,
        country_alpha2: "TW",
        country_alpha3: "TWN",
        country_eng_name: "Taiwan, Province of China",
        country_currency: 901,
        phone_prefix: "886",
        country_flag: "🇹🇼",
        is_country: true,
        country_primary_language: 30,
    },
    IsoCountryStatic {
        country_code: 162,
        country_alpha2: "CX",
        country_alpha3: "CXR",
        country_eng_name: "Christmas Island",
        country_currency: 36,
        phone_prefix: "61",
        country_flag: "🇨🇽",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 166,
        country_alpha2: "CC",
        country_alpha3: "CCK",
        country_eng_name: "Cocos (Keeling) Islands",
        country_currency: 36,
        phone_prefix: "61",
        country_flag: "🇨🇨",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 170,
        country_alpha2: "CO",
        country_alpha3: "COL",
        country_eng_name: "Colombia",
        country_currency: 170,
        phone_prefix: "57",
        country_flag: "🇨🇴",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 174,
        country_alpha2: "KM",
        country_alpha3: "COM",
        country_eng_name: "Comoros",
        country_currency: 174,
        phone_prefix: "269",
        country_flag: "🇰🇲",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 175,
        country_alpha2: "YT",
        country_alpha3: "MYT",
        country_eng_name: "Mayotte",
        country_currency: 978,
        phone_prefix: "262",
        country_flag: "🇾🇹",
        is_country: false,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 178,
        country_alpha2: "CG",
        country_alpha3: "COG",
        country_eng_name: "Congo",
        country_currency: 950,
        phone_prefix: "242",
        country_flag: "🇨🇬",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 180,
        country_alpha2: "CD",
        country_alpha3: "COD",
        country_eng_name: "Congo, Democratic Republic of the",
        country_currency: 950,
        phone_prefix: "243",
        country_flag: "🇨🇩",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 184,
        country_alpha2: "CK",
        country_alpha3: "COK",
        country_eng_name: "Cook Islands",
        country_currency: 554,
        phone_prefix: "682",
        country_flag: "🇨🇰",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 188,
        country_alpha2: "CR",
        country_alpha3: "CRI",
        country_eng_name: "Costa Rica",
        country_currency: 188,
        phone_prefix: "506",
        country_flag: "🇨🇷",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 191,
        country_alpha2: "HR",
        country_alpha3: "HRV",
        country_eng_name: "Croatia",
        country_currency: 978,
        phone_prefix: "385",
        country_flag: "🇭🇷",
        is_country: true,
        country_primary_language: 35,
    },
    IsoCountryStatic {
        country_code: 192,
        country_alpha2: "CU",
        country_alpha3: "CUB",
        country_eng_name: "Cuba",
        country_currency: 931,
        phone_prefix: "53",
        country_flag: "🇨🇺",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 196,
        country_alpha2: "CY",
        country_alpha3: "CYP",
        country_eng_name: "Cyprus",
        country_currency: 978,
        phone_prefix: "357",
        country_flag: "🇨🇾",
        is_country: true,
        country_primary_language: 53,
    },
    IsoCountryStatic {
        country_code: 203,
        country_alpha2: "CZ",
        country_alpha3: "CZE",
        country_eng_name: "Czechia",
        country_currency: 978,
        phone_prefix: "420",
        country_flag: "🇨🇿",
        is_country: true,
        country_primary_language: 36,
    },
    IsoCountryStatic {
        country_code: 204,
        country_alpha2: "BJ",
        country_alpha3: "BEN",
        country_eng_name: "Benin",
        country_currency: 952,
        phone_prefix: "229",
        country_flag: "🇧🇯",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 208,
        country_alpha2: "DK",
        country_alpha3: "DNK",
        country_eng_name: "Denmark",
        country_currency: 978,
        phone_prefix: "45",
        country_flag: "🇩🇰",
        is_country: true,
        country_primary_language: 37,
    },
    IsoCountryStatic {
        country_code: 212,
        country_alpha2: "DM",
        country_alpha3: "DMA",
        country_eng_name: "Dominica",
        country_currency: 951,
        phone_prefix: "1",
        country_flag: "🇩🇲",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 214,
        country_alpha2: "DO",
        country_alpha3: "DOM",
        country_eng_name: "Dominican Republic",
        country_currency: 214,
        phone_prefix: "1",
        country_flag: "🇩🇴",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 218,
        country_alpha2: "EC",
        country_alpha3: "ECU",
        country_eng_name: "Ecuador",
        country_currency: 840,
        phone_prefix: "593",
        country_flag: "🇪🇨",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 222,
        country_alpha2: "SV",
        country_alpha3: "SLV",
        country_eng_name: "El Salvador",
        country_currency: 222,
        phone_prefix: "503",
        country_flag: "🇸🇻",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 226,
        country_alpha2: "GQ",
        country_alpha3: "GNQ",
        country_eng_name: "Equatorial Guinea",
        country_currency: 950,
        phone_prefix: "240",
        country_flag: "🇬🇶",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 231,
        country_alpha2: "ET",
        country_alpha3: "ETH",
        country_eng_name: "Ethiopia",
        country_currency: 230,
        phone_prefix: "251",
        country_flag: "🇪🇹",
        is_country: true,
        country_primary_language: 6,
    },
    IsoCountryStatic {
        country_code: 232,
        country_alpha2: "ER",
        country_alpha3: "ERI",
        country_eng_name: "Eritrea",
        country_currency: 232,
        phone_prefix: "291",
        country_flag: "🇪🇷",
        is_country: true,
        country_primary_language: 158,
    },
    IsoCountryStatic {
        country_code: 233,
        country_alpha2: "EE",
        country_alpha3: "EST",
        country_eng_name: "Estonia",
        country_currency: 978,
        phone_prefix: "372",
        country_flag: "🇪🇪",
        is_country: true,
        country_primary_language: 43,
    },
    IsoCountryStatic {
        country_code: 234,
        country_alpha2: "FO",
        country_alpha3: "FRO",
        country_eng_name: "Faroe Islands",
        country_currency: 978,
        phone_prefix: "298",
        country_flag: "🇫🇴",
        is_country: false,
        country_primary_language: 45,
    },
    IsoCountryStatic {
        country_code: 238,
        country_alpha2: "FK",
        country_alpha3: "FLK",
        country_eng_name: "Falkland Islands (Malvinas)",
        country_currency: 826,
        phone_prefix: "500",
        country_flag: "🇫🇰",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 239,
        country_alpha2: "GS",
        country_alpha3: "SGS",
        country_eng_name: "South Georgia and the South Sandwich Islands",
        country_currency: 826,
        phone_prefix: "44",
        country_flag: "🇬🇸",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 242,
        country_alpha2: "FJ",
        country_alpha3: "FJI",
        country_eng_name: "Fiji",
        country_currency: 242,
        phone_prefix: "679",
        country_flag: "🇫🇯",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 246,
        country_alpha2: "FI",
        country_alpha3: "FIN",
        country_eng_name: "Finland",
        country_currency: 978,
        phone_prefix: "358",
        country_flag: "🇫🇮",
        is_country: true,
        country_primary_language: 47,
    },
    IsoCountryStatic {
        country_code: 248,
        country_alpha2: "AX",
        country_alpha3: "ALA",
        country_eng_name: "Åland Islands",
        country_currency: 978,
        phone_prefix: "358",
        country_flag: "🇦🇽",
        is_country: false,
        country_primary_language: 153,
    },
    IsoCountryStatic {
        country_code: 250,
        country_alpha2: "FR",
        country_alpha3: "FRA",
        country_eng_name: "France",
        country_currency: 978,
        phone_prefix: "33",
        country_flag: "🇫🇷",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 254,
        country_alpha2: "GF",
        country_alpha3: "GUF",
        country_eng_name: "French Guiana",
        country_currency: 978,
        phone_prefix: "594",
        country_flag: "🇬🇫",
        is_country: false,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 258,
        country_alpha2: "PF",
        country_alpha3: "PYF",
        country_eng_name: "French Polynesia",
        country_currency: 953,
        phone_prefix: "689",
        country_flag: "🇵🇫",
        is_country: false,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 260,
        country_alpha2: "TF",
        country_alpha3: "ATF",
        country_eng_name: "French Southern Territories",
        country_currency: 978,
        phone_prefix: "33",
        country_flag: "🇹🇫",
        is_country: false,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 262,
        country_alpha2: "DJ",
        country_alpha3: "DJI",
        country_eng_name: "Djibouti",
        country_currency: 262,
        phone_prefix: "253",
        country_flag: "🇩🇯",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 266,
        country_alpha2: "GA",
        country_alpha3: "GAB",
        country_eng_name: "Gabon",
        country_currency: 950,
        phone_prefix: "241",
        country_flag: "🇬🇦",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 268,
        country_alpha2: "GE",
        country_alpha3: "GEO",
        country_eng_name: "Georgia",
        country_currency: 981,
        phone_prefix: "995",
        country_flag: "🇬🇪",
        is_country: true,
        country_primary_language: 51,
    },
    IsoCountryStatic {
        country_code: 270,
        country_alpha2: "GM",
        country_alpha3: "GMB",
        country_eng_name: "Gambia",
        country_currency: 270,
        phone_prefix: "220",
        country_flag: "🇬🇲",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 275,
        country_alpha2: "PS",
        country_alpha3: "PSE",
        country_eng_name: "Palestine, State of",
        country_currency: 376,
        phone_prefix: "970",
        country_flag: "🇵🇸",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 276,
        country_alpha2: "DE",
        country_alpha3: "DEU",
        country_eng_name: "Germany",
        country_currency: 978,
        phone_prefix: "49",
        country_flag: "🇩🇪",
        is_country: true,
        country_primary_language: 52,
    },
    IsoCountryStatic {
        country_code: 288,
        country_alpha2: "GH",
        country_alpha3: "GHA",
        country_eng_name: "Ghana",
        country_currency: 936,
        phone_prefix: "233",
        country_flag: "🇬🇭",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 292,
        country_alpha2: "GI",
        country_alpha3: "GIB",
        country_eng_name: "Gibraltar",
        country_currency: 292,
        phone_prefix: "350",
        country_flag: "🇬🇮",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 296,
        country_alpha2: "KI",
        country_alpha3: "KIR",
        country_eng_name: "Kiribati",
        country_currency: 36,
        phone_prefix: "686",
        country_flag: "🇰🇮",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 300,
        country_alpha2: "GR",
        country_alpha3: "GRC",
        country_eng_name: "Greece",
        country_currency: 978,
        phone_prefix: "30",
        country_flag: "🇬🇷",
        is_country: true,
        country_primary_language: 53,
    },
    IsoCountryStatic {
        country_code: 304,
        country_alpha2: "GL",
        country_alpha3: "GRL",
        country_eng_name: "Greenland",
        country_currency: 978,
        phone_prefix: "299",
        country_flag: "🇬🇱",
        is_country: false,
        country_primary_language: 75,
    },
    IsoCountryStatic {
        country_code: 308,
        country_alpha2: "GD",
        country_alpha3: "GRD",
        country_eng_name: "Grenada",
        country_currency: 951,
        phone_prefix: "1",
        country_flag: "🇬🇩",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 312,
        country_alpha2: "GP",
        country_alpha3: "GLP",
        country_eng_name: "Guadeloupe",
        country_currency: 978,
        phone_prefix: "590",
        country_flag: "🇬🇵",
        is_country: false,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 316,
        country_alpha2: "GU",
        country_alpha3: "GUM",
        country_eng_name: "Guam",
        country_currency: 840,
        phone_prefix: "1",
        country_flag: "🇬🇺",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 320,
        country_alpha2: "GT",
        country_alpha3: "GTM",
        country_eng_name: "Guatemala",
        country_currency: 320,
        phone_prefix: "502",
        country_flag: "🇬🇹",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 324,
        country_alpha2: "GN",
        country_alpha3: "GIN",
        country_eng_name: "Guinea",
        country_currency: 324,
        phone_prefix: "224",
        country_flag: "🇬🇳",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 328,
        country_alpha2: "GY",
        country_alpha3: "GUY",
        country_eng_name: "Guyana",
        country_currency: 328,
        phone_prefix: "592",
        country_flag: "🇬🇾",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 332,
        country_alpha2: "HT",
        country_alpha3: "HTI",
        country_eng_name: "Haiti",
        country_currency: 332,
        phone_prefix: "509",
        country_flag: "🇭🇹",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 334,
        country_alpha2: "HM",
        country_alpha3: "HMD",
        country_eng_name: "Heard Island and McDonald Islands",
        country_currency: 36,
        phone_prefix: "61",
        country_flag: "🇦🇺",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 336,
        country_alpha2: "VA",
        country_alpha3: "VAT",
        country_eng_name: "Holy See",
        country_currency: 978,
        phone_prefix: "39",
        country_flag: "🇻🇦",
        is_country: true,
        country_primary_language: 71,
    },
    IsoCountryStatic {
        country_code: 340,
        country_alpha2: "HN",
        country_alpha3: "HND",
        country_eng_name: "Honduras",
        country_currency: 340,
        phone_prefix: "504",
        country_flag: "🇭🇳",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 344,
        country_alpha2: "HK",
        country_alpha3: "HKG",
        country_eng_name: "Hong Kong",
        country_currency: 344,
        phone_prefix: "852",
        country_flag: "🇭🇰",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 348,
        country_alpha2: "HU",
        country_alpha3: "HUN",
        country_eng_name: "Hungary",
        country_currency: 348,
        phone_prefix: "36",
        country_flag: "🇭🇺",
        is_country: true,
        country_primary_language: 62,
    },
    IsoCountryStatic {
        country_code: 352,
        country_alpha2: "IS",
        country_alpha3: "ISL",
        country_eng_name: "Iceland",
        country_currency: 352,
        phone_prefix: "354",
        country_flag: "🇮🇸",
        is_country: true,
        country_primary_language: 70,
    },
    IsoCountryStatic {
        country_code: 356,
        country_alpha2: "IN",
        country_alpha3: "IND",
        country_eng_name: "India",
        country_currency: 356,
        phone_prefix: "91",
        country_flag: "🇮🇳",
        is_country: true,
        country_primary_language: 60,
    },
    IsoCountryStatic {
        country_code: 360,
        country_alpha2: "ID",
        country_alpha3: "IDN",
        country_eng_name: "Indonesia",
        country_currency: 360,
        phone_prefix: "62",
        country_flag: "🇮🇩",
        is_country: true,
        country_primary_language: 64,
    },
    IsoCountryStatic {
        country_code: 364,
        country_alpha2: "IR",
        country_alpha3: "IRN",
        country_eng_name: "Iran, Islamic Republic of",
        country_currency: 364,
        phone_prefix: "98",
        country_flag: "🇮🇷",
        is_country: true,
        country_primary_language: 126,
    },
    IsoCountryStatic {
        country_code: 368,
        country_alpha2: "IQ",
        country_alpha3: "IRQ",
        country_eng_name: "Iraq",
        country_currency: 368,
        phone_prefix: "964",
        country_flag: "🇮🇶",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 372,
        country_alpha2: "IE",
        country_alpha3: "IRL",
        country_eng_name: "Ireland",
        country_currency: 978,
        phone_prefix: "353",
        country_flag: "🇮🇪",
        is_country: true,
        country_primary_language: 66,
    },
    IsoCountryStatic {
        country_code: 376,
        country_alpha2: "IL",
        country_alpha3: "ISR",
        country_eng_name: "Israel",
        country_currency: 376,
        phone_prefix: "972",
        country_flag: "🇮🇱",
        is_country: true,
        country_primary_language: 58,
    },
    IsoCountryStatic {
        country_code: 380,
        country_alpha2: "IT",
        country_alpha3: "ITA",
        country_eng_name: "Italy",
        country_currency: 978,
        phone_prefix: "39",
        country_flag: "🇮🇹",
        is_country: true,
        country_primary_language: 71,
    },
    IsoCountryStatic {
        country_code: 384,
        country_alpha2: "CI",
        country_alpha3: "CIV",
        country_eng_name: "Côte d'Ivoire",
        country_currency: 952,
        phone_prefix: "225",
        country_flag: "🇨🇮",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 388,
        country_alpha2: "JM",
        country_alpha3: "JAM",
        country_eng_name: "Jamaica",
        country_currency: 388,
        phone_prefix: "1",
        country_flag: "🇯🇲",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 392,
        country_alpha2: "JP",
        country_alpha3: "JPN",
        country_eng_name: "Japan",
        country_currency: 392,
        phone_prefix: "81",
        country_flag: "🇯🇵",
        is_country: true,
        country_primary_language: 73,
    },
    IsoCountryStatic {
        country_code: 398,
        country_alpha2: "KZ",
        country_alpha3: "KAZ",
        country_eng_name: "Kazakhstan",
        country_currency: 398,
        phone_prefix: "7",
        country_flag: "🇰🇿",
        is_country: true,
        country_primary_language: 79,
    },
    IsoCountryStatic {
        country_code: 400,
        country_alpha2: "JO",
        country_alpha3: "JOR",
        country_eng_name: "Jordan",
        country_currency: 400,
        phone_prefix: "962",
        country_flag: "🇯🇴",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 404,
        country_alpha2: "KE",
        country_alpha3: "KEN",
        country_eng_name: "Kenya",
        country_currency: 404,
        phone_prefix: "254",
        country_flag: "🇰🇪",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 410,
        country_alpha2: "KR",
        country_alpha3: "KOR",
        country_eng_name: "Korea, Republic of",
        country_currency: 410,
        phone_prefix: "82",
        country_flag: "🇰🇷",
        is_country: true,
        country_primary_language: 86,
    },
    IsoCountryStatic {
        country_code: 414,
        country_alpha2: "KW",
        country_alpha3: "KWT",
        country_eng_name: "Kuwait",
        country_currency: 414,
        phone_prefix: "965",
        country_flag: "🇰🇼",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 417,
        country_alpha2: "KG",
        country_alpha3: "KGZ",
        country_eng_name: "Kyrgyzstan",
        country_currency: 417,
        phone_prefix: "996",
        country_flag: "🇰🇬",
        is_country: true,
        country_primary_language: 83,
    },
    IsoCountryStatic {
        country_code: 418,
        country_alpha2: "LA",
        country_alpha3: "LAO",
        country_eng_name: "Lao People's Democratic Republic",
        country_currency: 418,
        phone_prefix: "856",
        country_flag: "🇱🇦",
        is_country: true,
        country_primary_language: 94,
    },
    IsoCountryStatic {
        country_code: 422,
        country_alpha2: "LB",
        country_alpha3: "LBN",
        country_eng_name: "Lebanon",
        country_currency: 422,
        phone_prefix: "961",
        country_flag: "🇱🇧",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 426,
        country_alpha2: "LS",
        country_alpha3: "LSO",
        country_eng_name: "Lesotho",
        country_currency: 426,
        phone_prefix: "266",
        country_flag: "🇱🇸",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 428,
        country_alpha2: "LV",
        country_alpha3: "LVA",
        country_eng_name: "Latvia",
        country_currency: 978,
        phone_prefix: "371",
        country_flag: "🇱🇻",
        is_country: true,
        country_primary_language: 97,
    },
    IsoCountryStatic {
        country_code: 430,
        country_alpha2: "LR",
        country_alpha3: "LBR",
        country_eng_name: "Liberia",
        country_currency: 430,
        phone_prefix: "231",
        country_flag: "🇱🇷",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 434,
        country_alpha2: "LY",
        country_alpha3: "LBY",
        country_eng_name: "Libya",
        country_currency: 434,
        phone_prefix: "218",
        country_flag: "🇱🇾",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 438,
        country_alpha2: "LI",
        country_alpha3: "LIE",
        country_eng_name: "Liechtenstein",
        country_currency: 756,
        phone_prefix: "423",
        country_flag: "🇱🇮",
        is_country: true,
        country_primary_language: 52,
    },
    IsoCountryStatic {
        country_code: 440,
        country_alpha2: "LT",
        country_alpha3: "LTU",
        country_eng_name: "Lithuania",
        country_currency: 978,
        phone_prefix: "370",
        country_flag: "🇱🇹",
        is_country: true,
        country_primary_language: 95,
    },
    IsoCountryStatic {
        country_code: 442,
        country_alpha2: "LU",
        country_alpha3: "LUX",
        country_eng_name: "Luxembourg",
        country_currency: 978,
        phone_prefix: "352",
        country_flag: "🇱🇺",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 446,
        country_alpha2: "MO",
        country_alpha3: "MAC",
        country_eng_name: "Macao",
        country_currency: 446,
        phone_prefix: "853",
        country_flag: "🇲🇴",
        is_country: false,
        country_primary_language: 30,
    },
    IsoCountryStatic {
        country_code: 450,
        country_alpha2: "MG",
        country_alpha3: "MDG",
        country_eng_name: "Madagascar",
        country_currency: 969,
        phone_prefix: "261",
        country_flag: "🇲🇬",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 454,
        country_alpha2: "MW",
        country_alpha3: "MWI",
        country_eng_name: "Malawi",
        country_currency: 454,
        phone_prefix: "265",
        country_flag: "🇲🇼",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 458,
        country_alpha2: "MY",
        country_alpha3: "MYS",
        country_eng_name: "Malaysia",
        country_currency: 458,
        phone_prefix: "60",
        country_flag: "🇲🇾",
        is_country: true,
        country_primary_language: 101,
    },
    IsoCountryStatic {
        country_code: 462,
        country_alpha2: "MV",
        country_alpha3: "MDV",
        country_eng_name: "Maldives",
        country_currency: 462,
        phone_prefix: "960",
        country_flag: "🇲🇻",
        is_country: true,
        country_primary_language: 38,
    },
    IsoCountryStatic {
        country_code: 466,
        country_alpha2: "ML",
        country_alpha3: "MLI",
        country_eng_name: "Mali",
        country_currency: 952,
        phone_prefix: "223",
        country_flag: "🇲🇱",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 470,
        country_alpha2: "MT",
        country_alpha3: "MLT",
        country_eng_name: "Malta",
        country_currency: 978,
        phone_prefix: "356",
        country_flag: "🇲🇹",
        is_country: true,
        country_primary_language: 103,
    },
    IsoCountryStatic {
        country_code: 474,
        country_alpha2: "MQ",
        country_alpha3: "MTQ",
        country_eng_name: "Martinique",
        country_currency: 978,
        phone_prefix: "596",
        country_flag: "🇲🇶",
        is_country: false,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 478,
        country_alpha2: "MR",
        country_alpha3: "MRT",
        country_eng_name: "Mauritania",
        country_currency: 929,
        phone_prefix: "222",
        country_flag: "🇲🇷",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 480,
        country_alpha2: "MU",
        country_alpha3: "MUS",
        country_eng_name: "Mauritius",
        country_currency: 480,
        phone_prefix: "230",
        country_flag: "🇲🇺",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 484,
        country_alpha2: "MX",
        country_alpha3: "MEX",
        country_eng_name: "Mexico",
        country_currency: 484,
        phone_prefix: "52",
        country_flag: "🇲🇽",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 492,
        country_alpha2: "MC",
        country_alpha3: "MCO",
        country_eng_name: "Monaco",
        country_currency: 978,
        phone_prefix: "377",
        country_flag: "🇲🇨",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 496,
        country_alpha2: "MN",
        country_alpha3: "MNG",
        country_eng_name: "Mongolia",
        country_currency: 496,
        phone_prefix: "976",
        country_flag: "🇲🇳",
        is_country: true,
        country_primary_language: 107,
    },
    IsoCountryStatic {
        country_code: 498,
        country_alpha2: "MD",
        country_alpha3: "MDA",
        country_eng_name: "Moldova, Republic of",
        country_currency: 498,
        phone_prefix: "373",
        country_flag: "🇲🇩",
        is_country: true,
        country_primary_language: 133,
    },
    IsoCountryStatic {
        country_code: 499,
        country_alpha2: "ME",
        country_alpha3: "MNE",
        country_eng_name: "Montenegro",
        country_currency: 978,
        phone_prefix: "382",
        country_flag: "🇲🇪",
        is_country: true,
        country_primary_language: 141,
    },
    IsoCountryStatic {
        country_code: 500,
        country_alpha2: "MS",
        country_alpha3: "MSR",
        country_eng_name: "Montserrat",
        country_currency: 951,
        phone_prefix: "1",
        country_flag: "🇲🇸",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 504,
        country_alpha2: "MA",
        country_alpha3: "MAR",
        country_eng_name: "Morocco",
        country_currency: 504,
        phone_prefix: "212",
        country_flag: "🇲🇦",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 508,
        country_alpha2: "MZ",
        country_alpha3: "MOZ",
        country_eng_name: "Mozambique",
        country_currency: 943,
        phone_prefix: "258",
        country_flag: "🇲🇿",
        is_country: true,
        country_primary_language: 129,
    },
    IsoCountryStatic {
        country_code: 512,
        country_alpha2: "OM",
        country_alpha3: "OMN",
        country_eng_name: "Oman",
        country_currency: 512,
        phone_prefix: "968",
        country_flag: "🇴🇲",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 516,
        country_alpha2: "NA",
        country_alpha3: "NAM",
        country_eng_name: "Namibia",
        country_currency: 516,
        phone_prefix: "264",
        country_flag: "🇳🇦",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 520,
        country_alpha2: "NR",
        country_alpha3: "NRU",
        country_eng_name: "Nauru",
        country_currency: 36,
        phone_prefix: "674",
        country_flag: "🇳🇷",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 524,
        country_alpha2: "NP",
        country_alpha3: "NPL",
        country_eng_name: "Nepal",
        country_currency: 524,
        phone_prefix: "977",
        country_flag: "🇳🇵",
        is_country: true,
        country_primary_language: 111,
    },
    IsoCountryStatic {
        country_code: 528,
        country_alpha2: "NL",
        country_alpha3: "NLD",
        country_eng_name: "Netherlands, Kingdom of the",
        country_currency: 978,
        phone_prefix: "31",
        country_flag: "🇳🇱",
        is_country: true,
        country_primary_language: 39,
    },
    IsoCountryStatic {
        country_code: 531,
        country_alpha2: "CW",
        country_alpha3: "CUW",
        country_eng_name: "Curaçao",
        country_currency: 978,
        phone_prefix: "599",
        country_flag: "🇨🇼",
        is_country: false,
        country_primary_language: 39,
    },
    IsoCountryStatic {
        country_code: 533,
        country_alpha2: "AW",
        country_alpha3: "ABW",
        country_eng_name: "Aruba",
        country_currency: 533,
        phone_prefix: "297",
        country_flag: "🇦🇼",
        is_country: false,
        country_primary_language: 39,
    },
    IsoCountryStatic {
        country_code: 534,
        country_alpha2: "SX",
        country_alpha3: "SXM",
        country_eng_name: "Sint Maarten (Dutch part)",
        country_currency: 978,
        phone_prefix: "1",
        country_flag: "🇸🇽",
        is_country: false,
        country_primary_language: 39,
    },
    IsoCountryStatic {
        country_code: 535,
        country_alpha2: "BQ",
        country_alpha3: "BES",
        country_eng_name: "Bonaire, Sint Eustatius and Saba",
        country_currency: 978,
        phone_prefix: "599",
        country_flag: "🇧🇶",
        is_country: false,
        country_primary_language: 39,
    },
    IsoCountryStatic {
        country_code: 540,
        country_alpha2: "NC",
        country_alpha3: "NCL",
        country_eng_name: "New Caledonia",
        country_currency: 953,
        phone_prefix: "687",
        country_flag: "🇳🇨",
        is_country: false,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 548,
        country_alpha2: "VU",
        country_alpha3: "VUT",
        country_eng_name: "Vanuatu",
        country_currency: 548,
        phone_prefix: "678",
        country_flag: "🇻🇺",
        is_country: true,
        country_primary_language: 21,
    },
    IsoCountryStatic {
        country_code: 554,
        country_alpha2: "NZ",
        country_alpha3: "NZL",
        country_eng_name: "New Zealand",
        country_currency: 554,
        phone_prefix: "64",
        country_flag: "🇳🇿",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 558,
        country_alpha2: "NI",
        country_alpha3: "NIC",
        country_eng_name: "Nicaragua",
        country_currency: 558,
        phone_prefix: "505",
        country_flag: "🇳🇮",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 562,
        country_alpha2: "NE",
        country_alpha3: "NER",
        country_eng_name: "Niger",
        country_currency: 952,
        phone_prefix: "227",
        country_flag: "🇳🇪",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 566,
        country_alpha2: "NG",
        country_alpha3: "NGA",
        country_eng_name: "Nigeria",
        country_currency: 566,
        phone_prefix: "234",
        country_flag: "🇳🇬",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 570,
        country_alpha2: "NU",
        country_alpha3: "NIU",
        country_eng_name: "Niue",
        country_currency: 554,
        phone_prefix: "683",
        country_flag: "🇳🇺",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 574,
        country_alpha2: "NF",
        country_alpha3: "NFK",
        country_eng_name: "Norfolk Island",
        country_currency: 36,
        phone_prefix: "672",
        country_flag: "🇳🇫",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 578,
        country_alpha2: "NO",
        country_alpha3: "NOR",
        country_eng_name: "Norway",
        country_currency: 578,
        phone_prefix: "47",
        country_flag: "🇳🇴",
        is_country: true,
        country_primary_language: 115,
    },
    IsoCountryStatic {
        country_code: 580,
        country_alpha2: "MP",
        country_alpha3: "MNP",
        country_eng_name: "Northern Mariana Islands",
        country_currency: 840,
        phone_prefix: "1",
        country_flag: "🇲🇵",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 581,
        country_alpha2: "UM",
        country_alpha3: "UMI",
        country_eng_name: "United States Minor Outlying Islands",
        country_currency: 840,
        phone_prefix: "1",
        country_flag: "🇺🇲",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 583,
        country_alpha2: "FM",
        country_alpha3: "FSM",
        country_eng_name: "Micronesia, Federated States of",
        country_currency: 840,
        phone_prefix: "691",
        country_flag: "🇫🇲",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 584,
        country_alpha2: "MH",
        country_alpha3: "MHL",
        country_eng_name: "Marshall Islands",
        country_currency: 840,
        phone_prefix: "692",
        country_flag: "🇲🇭",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 585,
        country_alpha2: "PW",
        country_alpha3: "PLW",
        country_eng_name: "Palau",
        country_currency: 840,
        phone_prefix: "680",
        country_flag: "🇵🇼",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 586,
        country_alpha2: "PK",
        country_alpha3: "PAK",
        country_eng_name: "Pakistan",
        country_currency: 586,
        phone_prefix: "92",
        country_flag: "🇵🇰",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 591,
        country_alpha2: "PA",
        country_alpha3: "PAN",
        country_eng_name: "Panama",
        country_currency: 590,
        phone_prefix: "507",
        country_flag: "🇵🇦",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 598,
        country_alpha2: "PG",
        country_alpha3: "PNG",
        country_eng_name: "Papua New Guinea",
        country_currency: 598,
        phone_prefix: "675",
        country_flag: "🇵🇬",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 600,
        country_alpha2: "PY",
        country_alpha3: "PRY",
        country_eng_name: "Paraguay",
        country_currency: 600,
        phone_prefix: "595",
        country_flag: "🇵🇾",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 604,
        country_alpha2: "PE",
        country_alpha3: "PER",
        country_eng_name: "Peru",
        country_currency: 604,
        phone_prefix: "51",
        country_flag: "🇵🇪",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 608,
        country_alpha2: "PH",
        country_alpha3: "PHL",
        country_eng_name: "Philippines",
        country_currency: 608,
        phone_prefix: "63",
        country_flag: "🇵🇭",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 612,
        country_alpha2: "PN",
        country_alpha3: "PCN",
        country_eng_name: "Pitcairn",
        country_currency: 826,
        phone_prefix: "44",
        country_flag: "🇵🇳",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 616,
        country_alpha2: "PL",
        country_alpha3: "POL",
        country_eng_name: "Poland",
        country_currency: 985,
        phone_prefix: "48",
        country_flag: "🇵🇱",
        is_country: true,
        country_primary_language: 127,
    },
    IsoCountryStatic {
        country_code: 620,
        country_alpha2: "PT",
        country_alpha3: "PRT",
        country_eng_name: "Portugal",
        country_currency: 978,
        phone_prefix: "351",
        country_flag: "🇵🇹",
        is_country: true,
        country_primary_language: 129,
    },
    IsoCountryStatic {
        country_code: 624,
        country_alpha2: "GW",
        country_alpha3: "GNB",
        country_eng_name: "Guinea-Bissau",
        country_currency: 952,
        phone_prefix: "245",
        country_flag: "🇬🇼",
        is_country: true,
        country_primary_language: 129,
    },
    IsoCountryStatic {
        country_code: 626,
        country_alpha2: "TL",
        country_alpha3: "TLS",
        country_eng_name: "Timor-Leste",
        country_currency: 840,
        phone_prefix: "670",
        country_flag: "🇹🇱",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 630,
        country_alpha2: "PR",
        country_alpha3: "PRI",
        country_eng_name: "Puerto Rico",
        country_currency: 840,
        phone_prefix: "1",
        country_flag: "🇵🇷",
        is_country: false,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 634,
        country_alpha2: "QA",
        country_alpha3: "QAT",
        country_eng_name: "Qatar",
        country_currency: 634,
        phone_prefix: "974",
        country_flag: "🇶🇦",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 638,
        country_alpha2: "RE",
        country_alpha3: "REU",
        country_eng_name: "Réunion",
        country_currency: 978,
        phone_prefix: "262",
        country_flag: "🇷🇪",
        is_country: false,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 642,
        country_alpha2: "RO",
        country_alpha3: "ROU",
        country_eng_name: "Romania",
        country_currency: 946,
        phone_prefix: "40",
        country_flag: "🇷🇴",
        is_country: true,
        country_primary_language: 133,
    },
    IsoCountryStatic {
        country_code: 643,
        country_alpha2: "RU",
        country_alpha3: "RUS",
        country_eng_name: "Russian Federation",
        country_currency: 643,
        phone_prefix: "7",
        country_flag: "🇷🇺",
        is_country: true,
        country_primary_language: 134,
    },
    IsoCountryStatic {
        country_code: 646,
        country_alpha2: "RW",
        country_alpha3: "RWA",
        country_eng_name: "Rwanda",
        country_currency: 646,
        phone_prefix: "250",
        country_flag: "🇷🇼",
        is_country: true,
        country_primary_language: 82,
    },
    IsoCountryStatic {
        country_code: 652,
        country_alpha2: "BL",
        country_alpha3: "BLM",
        country_eng_name: "Saint Barthélemy",
        country_currency: 978,
        phone_prefix: "590",
        country_flag: "🇧🇱",
        is_country: false,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 654,
        country_alpha2: "SH",
        country_alpha3: "SHN",
        country_eng_name: "Saint Helena, Ascension and Tristan da Cunha",
        country_currency: 978,
        phone_prefix: "290",
        country_flag: "🇸🇭",
        is_country: false,
        country_primary_language: 129,
    },
    IsoCountryStatic {
        country_code: 659,
        country_alpha2: "KN",
        country_alpha3: "KNA",
        country_eng_name: "Saint Kitts and Nevis",
        country_currency: 951,
        phone_prefix: "1",
        country_flag: "🇰🇳",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 660,
        country_alpha2: "AI",
        country_alpha3: "AIA",
        country_eng_name: "Anguilla",
        country_currency: 951,
        phone_prefix: "1",
        country_flag: "🇦🇮",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 662,
        country_alpha2: "LC",
        country_alpha3: "LCA",
        country_eng_name: "Saint Lucia",
        country_currency: 951,
        phone_prefix: "1",
        country_flag: "🇱🇨",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 663,
        country_alpha2: "MF",
        country_alpha3: "MAF",
        country_eng_name: "Saint Martin (French part)",
        country_currency: 978,
        phone_prefix: "590",
        country_flag: "🇲🇫",
        is_country: false,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 666,
        country_alpha2: "PM",
        country_alpha3: "SPM",
        country_eng_name: "Saint Pierre and Miquelon",
        country_currency: 978,
        phone_prefix: "508",
        country_flag: "🇵🇲",
        is_country: false,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 670,
        country_alpha2: "VC",
        country_alpha3: "VCT",
        country_eng_name: "Saint Vincent and the Grenadines",
        country_currency: 951,
        phone_prefix: "1",
        country_flag: "🇻🇨",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 674,
        country_alpha2: "SM",
        country_alpha3: "SMR",
        country_eng_name: "San Marino",
        country_currency: 978,
        phone_prefix: "378",
        country_flag: "🇸🇲",
        is_country: true,
        country_primary_language: 71,
    },
    IsoCountryStatic {
        country_code: 678,
        country_alpha2: "ST",
        country_alpha3: "STP",
        country_eng_name: "Sao Tome and Principe",
        country_currency: 930,
        phone_prefix: "239",
        country_flag: "🇸🇹",
        is_country: true,
        country_primary_language: 129,
    },
    IsoCountryStatic {
        country_code: 682,
        country_alpha2: "SA",
        country_alpha3: "SAU",
        country_eng_name: "Saudi Arabia",
        country_currency: 682,
        phone_prefix: "966",
        country_flag: "🇸🇦",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 686,
        country_alpha2: "SN",
        country_alpha3: "SEN",
        country_eng_name: "Senegal",
        country_currency: 952,
        phone_prefix: "221",
        country_flag: "🇸🇳",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 688,
        country_alpha2: "RS",
        country_alpha3: "SRB",
        country_eng_name: "Serbia",
        country_currency: 941,
        phone_prefix: "381",
        country_flag: "🇷🇸",
        is_country: true,
        country_primary_language: 141,
    },
    IsoCountryStatic {
        country_code: 690,
        country_alpha2: "SC",
        country_alpha3: "SYC",
        country_eng_name: "Seychelles",
        country_currency: 690,
        phone_prefix: "248",
        country_flag: "🇸🇨",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 694,
        country_alpha2: "SL",
        country_alpha3: "SLE",
        country_eng_name: "Sierra Leone",
        country_currency: 694,
        phone_prefix: "232",
        country_flag: "🇸🇱",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 702,
        country_alpha2: "SG",
        country_alpha3: "SGP",
        country_eng_name: "Singapore",
        country_currency: 702,
        phone_prefix: "65",
        country_flag: "🇸🇬",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 703,
        country_alpha2: "SK",
        country_alpha3: "SVK",
        country_eng_name: "Slovakia",
        country_currency: 978,
        phone_prefix: "421",
        country_flag: "🇸🇰",
        is_country: true,
        country_primary_language: 145,
    },
    IsoCountryStatic {
        country_code: 704,
        country_alpha2: "VN",
        country_alpha3: "VNM",
        country_eng_name: "Viet Nam",
        country_currency: 704,
        phone_prefix: "84",
        country_flag: "🇻🇳",
        is_country: true,
        country_primary_language: 174,
    },
    IsoCountryStatic {
        country_code: 705,
        country_alpha2: "SI",
        country_alpha3: "SVN",
        country_eng_name: "Slovenia",
        country_currency: 978,
        phone_prefix: "386",
        country_flag: "🇸🇮",
        is_country: true,
        country_primary_language: 146,
    },
    IsoCountryStatic {
        country_code: 706,
        country_alpha2: "SO",
        country_alpha3: "SOM",
        country_eng_name: "Somalia",
        country_currency: 706,
        phone_prefix: "252",
        country_flag: "🇸🇴",
        is_country: true,
        country_primary_language: 147,
    },
    IsoCountryStatic {
        country_code: 710,
        country_alpha2: "ZA",
        country_alpha3: "ZAF",
        country_eng_name: "South Africa",
        country_currency: 710,
        phone_prefix: "27",
        country_flag: "🇿🇦",
        is_country: true,
        country_primary_language: 3,
    },
    IsoCountryStatic {
        country_code: 716,
        country_alpha2: "ZW",
        country_alpha3: "ZWE",
        country_eng_name: "Zimbabwe",
        country_currency: 840,
        phone_prefix: "263",
        country_flag: "🇿🇼",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 724,
        country_alpha2: "ES",
        country_alpha3: "ESP",
        country_eng_name: "Spain",
        country_currency: 978,
        phone_prefix: "34",
        country_flag: "🇪🇸",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 728,
        country_alpha2: "SS",
        country_alpha3: "SSD",
        country_eng_name: "South Sudan",
        country_currency: 728,
        phone_prefix: "211",
        country_flag: "🇸🇸",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 729,
        country_alpha2: "SD",
        country_alpha3: "SDN",
        country_eng_name: "Sudan",
        country_currency: 938,
        phone_prefix: "249",
        country_flag: "🇸🇩",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 732,
        country_alpha2: "EH",
        country_alpha3: "ESH",
        country_eng_name: "Western Sahara",
        country_currency: 504,
        phone_prefix: "212",
        country_flag: "🇪🇭",
        is_country: false,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 740,
        country_alpha2: "SR",
        country_alpha3: "SUR",
        country_eng_name: "Suriname",
        country_currency: 968,
        phone_prefix: "597",
        country_flag: "🇸🇷",
        is_country: true,
        country_primary_language: 39,
    },
    IsoCountryStatic {
        country_code: 744,
        country_alpha2: "SJ",
        country_alpha3: "SJM",
        country_eng_name: "Svalbard and Jan Mayen",
        country_currency: 578,
        phone_prefix: "47",
        country_flag: "🇳🇴",
        is_country: false,
        country_primary_language: 115,
    },
    IsoCountryStatic {
        country_code: 748,
        country_alpha2: "SZ",
        country_alpha3: "SWZ",
        country_eng_name: "Eswatini",
        country_currency: 748,
        phone_prefix: "268",
        country_flag: "🇸🇿",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 752,
        country_alpha2: "SE",
        country_alpha3: "SWE",
        country_eng_name: "Sweden",
        country_currency: 752,
        phone_prefix: "46",
        country_flag: "🇸🇪",
        is_country: true,
        country_primary_language: 153,
    },
    IsoCountryStatic {
        country_code: 756,
        country_alpha2: "CH",
        country_alpha3: "CHE",
        country_eng_name: "Switzerland",
        country_currency: 947,
        phone_prefix: "41",
        country_flag: "🇨🇭",
        is_country: true,
        country_primary_language: 52,
    },
    IsoCountryStatic {
        country_code: 760,
        country_alpha2: "SY",
        country_alpha3: "SYR",
        country_eng_name: "Syrian Arab Republic",
        country_currency: 760,
        phone_prefix: "963",
        country_flag: "🇸🇾",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 762,
        country_alpha2: "TJ",
        country_alpha3: "TJK",
        country_eng_name: "Tajikistan",
        country_currency: 972,
        phone_prefix: "992",
        country_flag: "🇹🇯",
        is_country: true,
        country_primary_language: 156,
    },
    IsoCountryStatic {
        country_code: 764,
        country_alpha2: "TH",
        country_alpha3: "THA",
        country_eng_name: "Thailand",
        country_currency: 764,
        phone_prefix: "66",
        country_flag: "🇹🇭",
        is_country: true,
        country_primary_language: 157,
    },
    IsoCountryStatic {
        country_code: 768,
        country_alpha2: "TG",
        country_alpha3: "TGO",
        country_eng_name: "Togo",
        country_currency: 952,
        phone_prefix: "228",
        country_flag: "🇹🇬",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 772,
        country_alpha2: "TK",
        country_alpha3: "TKL",
        country_eng_name: "Tokelau",
        country_currency: 554,
        phone_prefix: "690",
        country_flag: "🇹🇰",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 776,
        country_alpha2: "TO",
        country_alpha3: "TON",
        country_eng_name: "Tonga",
        country_currency: 776,
        phone_prefix: "676",
        country_flag: "🇹🇴",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 780,
        country_alpha2: "TT",
        country_alpha3: "TTO",
        country_eng_name: "Trinidad and Tobago",
        country_currency: 780,
        phone_prefix: "1",
        country_flag: "🇹🇹",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 784,
        country_alpha2: "AE",
        country_alpha3: "ARE",
        country_eng_name: "United Arab Emirates",
        country_currency: 784,
        phone_prefix: "971",
        country_flag: "🇦🇪",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 788,
        country_alpha2: "TN",
        country_alpha3: "TUN",
        country_eng_name: "Tunisia",
        country_currency: 788,
        phone_prefix: "216",
        country_flag: "🇹🇳",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 792,
        country_alpha2: "TR",
        country_alpha3: "TUR",
        country_eng_name: "Türkiye",
        country_currency: 949,
        phone_prefix: "90",
        country_flag: "🇹🇷",
        is_country: true,
        country_primary_language: 164,
    },
    IsoCountryStatic {
        country_code: 795,
        country_alpha2: "TM",
        country_alpha3: "TKM",
        country_eng_name: "Turkmenistan",
        country_currency: 934,
        phone_prefix: "993",
        country_flag: "🇹🇲",
        is_country: true,
        country_primary_language: 160,
    },
    IsoCountryStatic {
        country_code: 796,
        country_alpha2: "TC",
        country_alpha3: "TCA",
        country_eng_name: "Turks and Caicos Islands",
        country_currency: 951,
        phone_prefix: "1",
        country_flag: "🇹🇨",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 798,
        country_alpha2: "TV",
        country_alpha3: "TUV",
        country_eng_name: "Tuvalu",
        country_currency: 36,
        phone_prefix: "688",
        country_flag: "🇹🇻",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 800,
        country_alpha2: "UG",
        country_alpha3: "UGA",
        country_eng_name: "Uganda",
        country_currency: 800,
        phone_prefix: "256",
        country_flag: "🇺🇬",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 804,
        country_alpha2: "UA",
        country_alpha3: "UKR",
        country_eng_name: "Ukraine",
        country_currency: 980,
        phone_prefix: "380",
        country_flag: "🇺🇦",
        is_country: true,
        country_primary_language: 170,
    },
    IsoCountryStatic {
        country_code: 807,
        country_alpha2: "MK",
        country_alpha3: "MKD",
        country_eng_name: "North Macedonia",
        country_currency: 807,
        phone_prefix: "389",
        country_flag: "🇲🇰",
        is_country: true,
        country_primary_language: 99,
    },
    IsoCountryStatic {
        country_code: 818,
        country_alpha2: "EG",
        country_alpha3: "EGY",
        country_eng_name: "Egypt",
        country_currency: 818,
        phone_prefix: "20",
        country_flag: "🇪🇬",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 826,
        country_alpha2: "GB",
        country_alpha3: "GBR",
        country_eng_name: "United Kingdom of Great Britain and Northern Ireland",
        country_currency: 826,
        phone_prefix: "44",
        country_flag: "🇬🇧",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 831,
        country_alpha2: "GG",
        country_alpha3: "GGY",
        country_eng_name: "Guernsey",
        country_currency: 826,
        phone_prefix: "44",
        country_flag: "🇬🇬",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 832,
        country_alpha2: "JE",
        country_alpha3: "JEY",
        country_eng_name: "Jersey",
        country_currency: 826,
        phone_prefix: "44",
        country_flag: "🇯🇪",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 833,
        country_alpha2: "IM",
        country_alpha3: "IMN",
        country_eng_name: "Isle of Man",
        country_currency: 826,
        phone_prefix: "44",
        country_flag: "🇮🇲",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 834,
        country_alpha2: "TZ",
        country_alpha3: "TZA",
        country_eng_name: "Tanzania, United Republic of",
        country_currency: 834,
        phone_prefix: "255",
        country_flag: "🇹🇿",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 840,
        country_alpha2: "US",
        country_alpha3: "USA",
        country_eng_name: "United States of America",
        country_currency: 840,
        phone_prefix: "1",
        country_flag: "🇺🇸",
        is_country: true,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 850,
        country_alpha2: "VI",
        country_alpha3: "VIR",
        country_eng_name: "Virgin Islands (U.S.)",
        country_currency: 840,
        phone_prefix: "1",
        country_flag: "🇻🇮",
        is_country: false,
        country_primary_language: 41,
    },
    IsoCountryStatic {
        country_code: 854,
        country_alpha2: "BF",
        country_alpha3: "BFA",
        country_eng_name: "Burkina Faso",
        country_currency: 952,
        phone_prefix: "226",
        country_flag: "🇧🇫",
        is_country: true,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 858,
        country_alpha2: "UY",
        country_alpha3: "URY",
        country_eng_name: "Uruguay",
        country_currency: 858,
        phone_prefix: "598",
        country_flag: "🇺🇾",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 860,
        country_alpha2: "UZ",
        country_alpha3: "UZB",
        country_eng_name: "Uzbekistan",
        country_currency: 860,
        phone_prefix: "998",
        country_flag: "🇺🇿",
        is_country: true,
        country_primary_language: 172,
    },
    IsoCountryStatic {
        country_code: 862,
        country_alpha2: "VE",
        country_alpha3: "VEN",
        country_eng_name: "Venezuela, Bolivarian Republic of",
        country_currency: 926,
        phone_prefix: "58",
        country_flag: "🇻🇪",
        is_country: true,
        country_primary_language: 149,
    },
    IsoCountryStatic {
        country_code: 876,
        country_alpha2: "WF",
        country_alpha3: "WLF",
        country_eng_name: "Wallis and Futuna",
        country_currency: 953,
        phone_prefix: "681",
        country_flag: "🇼🇫",
        is_country: false,
        country_primary_language: 48,
    },
    IsoCountryStatic {
        country_code: 882,
        country_alpha2: "WS",
        country_alpha3: "WSM",
        country_eng_name: "Samoa",
        country_currency: 882,
        phone_prefix: "685",
        country_flag: "🇼🇸",
        is_country: true,
        country_primary_language: 139,
    },
    IsoCountryStatic {
        country_code: 887,
        country_alpha2: "YE",
        country_alpha3: "YEM",
        country_eng_name: "Yemen",
        country_currency: 886,
        phone_prefix: "967",
        country_flag: "🇾🇪",
        is_country: true,
        country_primary_language: 7,
    },
    IsoCountryStatic {
        country_code: 894,
        country_alpha2: "ZM",
        country_alpha3: "ZMB",
        country_eng_name: "Zambia",
        country_currency: 967,
        phone_prefix: "260",
        country_flag: "🇿🇲",
        is_country: true,
        country_primary_language: 41,
    },

];

/// Static index on country_code
pub fn by_code(code: i32) -> Option<&'static IsoCountryStatic> {
    ISO_COUNTRIES.iter().find(|c| c.country_code == code)
}

pub fn by_alpha2(alpha2: &str) -> Option<&'static IsoCountryStatic> {
    ISO_COUNTRIES.iter().find(|c| c.country_alpha2 == alpha2)
}

pub fn by_alpha3(alpha3: &str) -> Option<&'static IsoCountryStatic> {
    ISO_COUNTRIES.iter().find(|c| c.country_alpha3 == alpha3)
}
