[build]
rustflags = ["-Ctarget-cpu=native", "-Cpanic=unwind"]

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = [
    "-Ctarget-cpu=native",
    "-Cpanic=abort",
    "-C",
    "link-arg=--ld-path=/usr/bin/mold",
]

[unstable]
build-std = ["std", "core", "alloc", "panic_unwind"]
