INSERT INTO
    public.iso_currency (currency_code, currency_alpha3, currency_name)
VALUES
    (4, 'AFA', 'Afghani'),
    (8, 'ALL', 'Lek'),
    (12, 'DZD', 'Algerian Dinar'),
    (20, 'ADP', 'Andorran Peseta'),
    (31, 'AZM', 'Azerbaijanian Manat'),
    (32, 'ARS', 'Argentine Peso'),
    (36, 'AUD', 'Australian Dollar'),
    (40, 'ATS', 'Schilling'),
    (44, 'BSD', 'Bahamian Dollar'),
    (48, 'BHD', 'Bahraini Dinar'),
    (50, 'BDT', 'Taka'),
    (51, 'AMD', 'Armenian Dram'),
    (52, 'BBD', 'Barbados Dollar'),
    (56, 'BEF', 'Belgian Franc'),
    (60, 'BMD', 'Bermudian Dollar'),
    (64, 'BTN', 'Ngultrum'),
    (68, 'BOB', 'Boliviano'),
    (70, 'BAD', 'Dinar'),
    (72, 'BWP', 'Pula'),
    (84, 'BZD', 'Belize Dollar'),
    (90, 'SBD', 'Solomon Islands Dollar'),
    (96, 'BND', 'Brunei Dollar'),
    (104, 'MMK', 'Kyat'),
    (108, 'BIF', 'Burundi Franc'),
    (112, 'BYB', 'Belarusian Ruble'),
    (116, 'KHR', 'Riel'),
    (124, 'CAD', 'Canadian Dollar'),
    (132, 'CVE', 'Cabo Verde Escudo'),
    (136, 'KYD', 'Cayman Islands Dollar'),
    (144, 'LKR', 'Sri Lanka Rupee'),
    (152, 'CLP', 'Chilean Peso'),
    (156, 'CNY', 'Yuan Renminbi'),
    (170, 'COP', 'Colombian Peso'),
    (174, 'KMF', 'Comorian Franc'),
    (188, 'CRC', 'Costa Rican Colon'),
    (192, 'CUP', 'Cuban Peso'),
    (196, 'CYP', 'Cyprus Pound'),
    (214, 'DOP', 'Dominican Peso'),
    (218, 'ECS', 'Sucre'),
    (222, 'SVC', 'El Salvador Colon'),
    (226, 'GQE', 'Ekwele'),
    (230, 'ETB', 'Ethiopian Birr'),
    (232, 'ERN', 'Nakfa'),
    (233, 'EEK', 'Kroon'),
    (238, 'FKP', 'Falkland Islands Pound'),
    (242, 'FJD', 'Fiji Dollar'),
    (246, 'FIM', 'Markka'),
    (250, 'FRF', 'French Franc'),
    (262, 'DJF', 'Djibouti Franc'),
    (268, 'GEK', 'Georgian Coupon'),
    (270, 'GMD', 'Dalasi'),
    (276, 'DEM', 'Deutsche Mark'),
    (278, 'DDM', 'Mark der DDR'),
    (288, 'GHC', 'Cedi'),
    (292, 'GIP', 'Gibraltar Pound'),
    (300, 'GRD', 'Drachma'),
    (320, 'GTQ', 'Quetzal'),
    (324, 'GNF', 'Guinean Franc'),
    (328, 'GYD', 'Guyana Dollar'),
    (332, 'HTG', 'Gourde'),
    (340, 'HNL', 'Lempira'),
    (344, 'HKD', 'Hong Kong Dollar'),
    (348, 'HUF', 'Forint'),
    (352, 'ISK', 'Iceland Krona'),
    (356, 'INR', 'Indian Rupee'),
    (360, 'IDR', 'Rupiah'),
    (364, 'IRR', 'Iranian Rial'),
    (368, 'IQD', 'Iraqi Dinar'),
    (372, 'IEP', 'Irish Pound'),
    (376, 'ILS', 'New Israeli Sheqel'),
    (380, 'ITL', 'Italian Lira'),
    (388, 'JMD', 'Jamaican Dollar'),
    (392, 'JPY', 'Yen'),
    (398, 'KZT', 'Tenge'),
    (400, 'JOD', 'Jordanian Dinar'),
    (404, 'KES', 'Kenyan Shilling'),
    (408, 'KPW', 'North Korean Won'),
    (410, 'KRW', 'Won'),
    (414, 'KWD', 'Kuwaiti Dinar'),
    (417, 'KGS', 'Som'),
    (418, 'LAK', 'Lao Kip'),
    (422, 'LBP', 'Lebanese Pound'),
    (426, 'LSL', 'Loti'),
    (430, 'LRD', 'Liberian Dollar'),
    (434, 'LYD', 'Libyan Dinar'),
    (442, 'LUF', 'Luxembourg Franc'),
    (446, 'MOP', 'Pataca'),
    (450, 'MGF', 'Malagasy Franc'),
    (454, 'MWK', 'Malawi Kwacha'),
    (458, 'MYR', 'Malaysian Ringgit'),
    (462, 'MVR', 'Rufiyaa'),
    (466, 'MLF', 'Mali Franc'),
    (478, 'MRO', 'Ouguiya'),
    (480, 'MUR', 'Mauritius Rupee'),
    (484, 'MXN', 'Mexican Peso'),
    (496, 'MNT', 'Tugrik'),
    (498, 'MDL', 'Moldovan Leu'),
    (504, 'MAD', 'Moroccan Dirham'),
    (512, 'OMR', 'Rial Omani'),
    (516, 'NAD', 'Namibia Dollar'),
    (524, 'NPR', 'Nepalese Rupee'),
    (528, 'NLG', 'Netherlands Guilder'),
    (532, 'ANG', 'Netherlands Antillean Guilder'),
    (533, 'AWG', 'Aruban Florin'),
    (548, 'VUV', 'Vatu'),
    (554, 'NZD', 'New Zealand Dollar'),
    (558, 'NIO', 'Cordoba Oro'),
    (566, 'NGN', 'Naira'),
    (578, 'NOK', 'Norwegian Krone'),
    (586, 'PKR', 'Pakistan Rupee'),
    (590, 'PAB', 'Balboa'),
    (598, 'PGK', 'Kina'),
    (600, 'PYG', 'Guarani'),
    (604, 'PES', 'Sol'),
    (608, 'PHP', 'Philippine Peso'),
    (616, 'PLZ', 'Zloty'),
    (620, 'PTE', 'Portuguese Escudo'),
    (626, 'TPE', 'Timor Escudo'),
    (634, 'QAR', 'Qatari Rial'),
    (643, 'RUB', 'Russian Ruble'),
    (646, 'RWF', 'Rwanda Franc'),
    (654, 'SHP', 'Saint Helena Pound'),
    (678, 'STD', 'Dobra'),
    (682, 'SAR', 'Saudi Riyal'),
    (690, 'SCR', 'Seychelles Rupee'),
    (694, 'SLL', 'Leone'),
    (702, 'SGD', 'Singapore Dollar'),
    (703, 'SKK', 'Slovak Koruna'),
    (704, 'VND', 'Dong'),
    (705, 'SIT', 'Tolar'),
    (706, 'SOS', 'Somali Shilling'),
    (710, 'ZAR', 'Rand'),
    (720, 'YDD', 'Yemeni Dinar'),
    (724, 'ESP', 'Spanish Peseta'),
    (728, 'SSP', 'South Sudanese Pound'),
    (736, 'SDD', 'Sudanese Dinar'),
    (740, 'SRG', 'Surinam Guilder'),
    (748, 'SZL', 'Lilangeni'),
    (752, 'SEK', 'Swedish Krona'),
    (756, 'CHF', 'Swiss Franc'),
    (760, 'SYP', 'Syrian Pound'),
    (762, 'TJR', 'Tajik Ruble'),
    (764, 'THB', 'Baht'),
    (776, 'TOP', 'Pa’anga'),
    (780, 'TTD', 'Trinidad and Tobago Dollar'),
    (784, 'AED', 'UAE Dirham'),
    (788, 'TND', 'Tunisian Dinar'),
    (792, 'TRL', 'Old Turkish Lira'),
    (795, 'TMM', 'Turkmenistan Manat'),
    (800, 'UGX', 'Uganda Shilling'),
    (807, 'MKD', 'Denar'),
    (810, 'RUR', 'Russian Ruble'),
    (818, 'EGP', 'Egyptian Pound'),
    (826, 'GBP', 'Pound Sterling'),
    (834, 'TZS', 'Tanzanian Shilling'),
    (840, 'USD', 'US Dollar'),
    (858, 'UYU', 'Peso Uruguayo'),
    (860, 'UZS', 'Uzbekistan Sum'),
    (862, 'VEB', 'Bolivar'),
    (882, 'WST', 'Tala'),
    (886, 'YER', 'Yemeni Rial'),
    (894, 'ZMK', 'Zambian Kwacha'),
    (901, 'TWD', 'New Taiwan Dollar'),
    (924, 'ZWG', 'Zimbabwe Gold'),
    (925, 'SLE', 'Leone'),
    (926, 'VED', 'Bolívar Soberano'),
    (927, 'UYW', 'Unidad Previsional'),
    (928, 'VES', 'Bolívar Soberano'),
    (929, 'MRU', 'Ouguiya'),
    (930, 'STN', 'Dobra'),
    (931, 'CUC', 'Peso Convertible'),
    (932, 'ZWL', 'Zimbabwe Dollar'),
    (933, 'BYN', 'Belarusian Ruble'),
    (934, 'TMT', 'Turkmenistan New Manat'),
    (935, 'ZWR', 'Zimbabwe Dollar'),
    (936, 'GHS', 'Ghana Cedi'),
    (937, 'VEF', 'Bolivar Fuerte'),
    (938, 'SDG', 'Sudanese Pound'),
    (939, 'GHP', 'Ghana Cedi'),
    (941, 'RSD', 'Serbian Dinar'),
    (942, 'ZWN', 'Zimbabwe Dollar (new)'),
    (943, 'MZN', 'Mozambique Metical'),
    (944, 'AZN', 'Azerbaijan Manat'),
    (945, 'AYM', 'Azerbaijan Manat'),
    (946, 'RON', 'Romanian Leu'),
    (947, 'CHE', 'WIR Euro'),
    (949, 'TRY', 'Turkish Lira'),
    (950, 'XAF', 'CFA Franc BEAC'),
    (951, 'XCD', 'East Caribbean Dollar'),
    (952, 'XOF', 'CFA Franc BCEAO'),
    (953, 'XPF', 'CFP Franc'),
    (954, 'XEU', 'European Currency Unit (E.C.U)'),
    (959, 'XAU', 'Gold'),
    (960, 'XDR', 'SDR (Special Drawing Right)'),
    (961, 'XAG', 'Silver'),
    (962, 'XPT', 'Platinum'),
    (964, 'XPD', 'Palladium'),
    (965, 'XUA', 'ADB Unit of Account'),
    (967, 'ZMW', 'Zambian Kwacha'),
    (968, 'SRD', 'Surinam Dollar'),
    (969, 'MGA', 'Malagasy Ariary'),
    (970, 'COU', 'Unidad de Valor Real'),
    (971, 'AFN', 'Afghani'),
    (972, 'TJS', 'Somoni'),
    (973, 'AOA', 'Kwanza'),
    (974, 'BYR', 'Belarusian Ruble'),
    (975, 'BGN', 'Bulgarian Lev'),
    (976, 'CDF', 'Congolese Franc'),
    (977, 'BAM', 'Convertible Mark'),
    (978, 'EUR', 'Euro'),
    (980, 'UAH', 'Hryvnia'),
    (981, 'GEL', 'Lari'),
    (983, 'ECV', 'Unidad de Valor Constante (UVC)'),
    (984, 'BOV', 'Mvdol'),
    (985, 'PLN', 'Zloty'),
    (986, 'BRL', 'Brazilian Real'),
    (987, 'BRR', 'Cruzeiro Real'),
    (988, 'LUL', 'Luxembourg Financial Franc'),
    (989, 'LUC', 'Luxembourg Convertible Franc'),
    (990, 'CLF', 'Unidad de Fomento'),
    (991, 'ZAL', 'Financial Rand'),
    (992, 'BEL', 'Financial Franc'),
    (993, 'BEC', 'Convertible Franc'),
    (994, 'XSU', 'Sucre'),
    (996, 'ESA', 'Spanish Peseta'),
    (997, 'USN', 'US Dollar (Next day)'),
    (998, 'USS', 'US Dollar (Same day)');
